using System.Globalization;
using Dbm.Core.Catalog;

namespace Dbm.Core.Matching;

public enum CompatLevel { Exact, Widening, Risky, Incompatible }

public sealed record ColumnType(string DataType, int MaxLength, int Precision, int Scale)
{
    public static ColumnType From(ColumnInfo c) => new(c.DataType.ToLowerInvariant(), c.MaxLength, c.Precision, c.Scale);

    /// <summary>Parses declaration text such as "int", "nvarchar(50)", "varchar(max)", "decimal(19,4)", "datetime2(3)".
    /// Lengths follow the catalog convention: characters for (n)char/(n)varchar, bytes for (var)binary, -1 = max, 0 otherwise.</summary>
    public static ColumnType Parse(string declaration)
    {
        var text = declaration.Trim().ToLowerInvariant();
        var open = text.IndexOf('(');
        var name = open < 0 ? text : text[..open].Trim();
        var args = open < 0
            ? Array.Empty<string>()
            : text[(open + 1)..text.LastIndexOf(')')].Split(',', StringSplitOptions.TrimEntries);
        int Arg(int index, int fallback) => args.Length <= index ? fallback
            : args[index] == "max" ? -1 : int.Parse(args[index], CultureInfo.InvariantCulture);
        return name switch
        {
            "char" or "nchar" or "binary" or "varchar" or "nvarchar" or "varbinary" => new(name, Arg(0, 1), 0, 0),
            "decimal" or "numeric" => new(name, 0, Arg(0, 18), Arg(1, 0)),
            "money" => new(name, 0, 19, 4),
            "smallmoney" => new(name, 0, 10, 4),
            "float" => new(name, 0, Arg(0, 53), 0),
            "real" => new(name, 0, 24, 0),
            "tinyint" => new(name, 0, 3, 0),
            "smallint" => new(name, 0, 5, 0),
            "int" => new(name, 0, 10, 0),
            "bigint" => new(name, 0, 19, 0),
            "bit" => new(name, 0, 1, 0),
            "date" => new(name, 0, 10, 0),
            "smalldatetime" => new(name, 0, 16, 0),
            "datetime" => new(name, 0, 23, 3),
            "time" or "datetime2" or "datetimeoffset" => new(name, 0, 0, Arg(0, 7)),
            _ => new(name, 0, 0, 0)
        };
    }
}

public sealed record TypeCompatResult(CompatLevel Level, double Score, string? Risk);

public static class TypeCompat
{
    private enum Fam { Int, Dec, Approx, Bit, Str, Bin, Date, Time, DateTime, Guid, Xml, Variant, Spatial, Hier, RowVer, Other }

    // Len: characters or bytes, long.MaxValue = max. P: integer digits (Int), precision (Dec/Approx). S: scale / fractional-second digits.
    private readonly record struct N(string Name, Fam Fam, long Len, int P, int S, bool Unicode = false, int Rank = 0, bool Offset = false);

    private const long Max = long.MaxValue;
    private static readonly TypeCompatResult ExactResult = new(CompatLevel.Exact, 1.0, null);
    private static readonly TypeCompatResult WideningResult = new(CompatLevel.Widening, 0.9, null);
    private static readonly TypeCompatResult RawBytes = new(CompatLevel.Risky, 0.5, "stored as raw bytes");

    public static TypeCompatResult Check(ColumnType src, ColumnType tgt, ColumnProfile? srcProfile = null)
    {
        var s = Norm(src);
        var t = Norm(tgt);
        if (t.Fam == Fam.RowVer) return Incompatible("rowversion columns are generated by the server and cannot be written");
        if (s.Name == t.Name && s.Len == t.Len && s.P == t.P && s.S == t.S) return ExactResult;
        if (s.Fam == Fam.Other || t.Fam == Fam.Other) return Risky($"unrecognised type conversion {s.Name} -> {t.Name}");
        var p = srcProfile is { SampledRows: > 0 } ? srcProfile : null;
        return s.Fam switch
        {
            Fam.Int => FromInt(s, t, p),
            Fam.Dec => FromDec(s, t, p),
            Fam.Approx => FromApprox(s, t),
            Fam.Bit => FromBit(s, t),
            Fam.Str => FromStr(s, t, p),
            Fam.Bin or Fam.RowVer => FromBin(s, t, p),
            Fam.Date => FromDate(s, t, p),
            Fam.Time => FromTime(s, t),
            Fam.DateTime => FromDateTime(s, t, p),
            Fam.Guid => FromGuid(s, t),
            Fam.Xml => t.Fam switch { Fam.Str => StrToStr(s, t, p), Fam.Bin => RawBytes, _ => Cannot(s, t) },
            Fam.Variant => t.Fam is Fam.Xml or Fam.Spatial or Fam.Hier ? Cannot(s, t) : Risky("conversion may fail"),
            Fam.Spatial => t.Fam switch
            {
                Fam.Spatial => Risky("needs a WKT round-trip (STAsText / STGeomFromText)"),
                Fam.Str => Risky("needs .STAsText()"),
                Fam.Bin => RawBytes,
                _ => Cannot(s, t)
            },
            Fam.Hier => t.Fam switch
            {
                Fam.Str => t.Len >= 4000 ? WideningResult : Risky("may truncate (needs up to 4000 characters)"),
                Fam.Bin => RawBytes,
                _ => Cannot(s, t)
            },
            _ => Cannot(s, t)
        };
    }

    /// <summary>Coarse family name used by the auto-mapper's profile scoring.</summary>
    public static string Family(string dataType) => Norm(new ColumnType(dataType.ToLowerInvariant(), 0, 0, 0)).Fam switch
    {
        Fam.Int => "integer",
        Fam.Dec => "decimal",
        Fam.Approx => "float",
        Fam.Bit => "bit",
        Fam.Str => "string",
        Fam.Bin => "binary",
        Fam.Date => "date",
        Fam.Time => "time",
        Fam.DateTime => "datetime",
        Fam.Guid => "guid",
        Fam.Xml => "xml",
        Fam.Variant => "variant",
        Fam.Spatial => "spatial",
        Fam.Hier => "hierarchyid",
        Fam.RowVer => "rowversion",
        _ => "other"
    };

    private static N Norm(ColumnType c)
    {
        var name = c.DataType.ToLowerInvariant();
        long Len(int n) => n < 0 ? Max : n;
        return name switch
        {
            "tinyint" => new(name, Fam.Int, 0, 3, 0, Rank: 1),
            "smallint" => new(name, Fam.Int, 0, 5, 0, Rank: 2),
            "int" => new(name, Fam.Int, 0, 10, 0, Rank: 3),
            "bigint" => new(name, Fam.Int, 0, 19, 0, Rank: 4),
            "decimal" or "numeric" => new(name, Fam.Dec, 0, c.Precision > 0 ? c.Precision : 18, c.Scale),
            "money" => new(name, Fam.Dec, 0, 19, 4),
            "smallmoney" => new(name, Fam.Dec, 0, 10, 4),
            "float" => new(name, Fam.Approx, 0, c.Precision is > 0 and <= 24 ? 24 : 53, 0),
            "real" => new(name, Fam.Approx, 0, 24, 0),
            "bit" => new(name, Fam.Bit, 0, 1, 0),
            "char" or "varchar" => new(name, Fam.Str, Len(c.MaxLength), 0, 0),
            "text" => new(name, Fam.Str, Max, 0, 0),
            "nchar" or "nvarchar" => new(name, Fam.Str, Len(c.MaxLength), 0, 0, Unicode: true),
            "ntext" => new(name, Fam.Str, Max, 0, 0, Unicode: true),
            "binary" or "varbinary" => new(name, Fam.Bin, Len(c.MaxLength), 0, 0),
            "image" => new(name, Fam.Bin, Max, 0, 0),
            "timestamp" or "rowversion" => new("rowversion", Fam.RowVer, 8, 0, 0),
            "date" => new(name, Fam.Date, 0, 0, 0),
            "time" => new(name, Fam.Time, 0, 0, c.Scale),
            "smalldatetime" => new(name, Fam.DateTime, 0, 0, 0),
            "datetime" => new(name, Fam.DateTime, 0, 0, 3),
            "datetime2" => new(name, Fam.DateTime, 0, 0, c.Scale),
            "datetimeoffset" => new(name, Fam.DateTime, 0, 0, c.Scale, Offset: true),
            "uniqueidentifier" => new(name, Fam.Guid, 0, 0, 0),
            "xml" => new(name, Fam.Xml, Max, 0, 0, Unicode: true),
            "sql_variant" => new(name, Fam.Variant, 0, 0, 0),
            "geography" or "geometry" => new(name, Fam.Spatial, 0, 0, 0),
            "hierarchyid" => new(name, Fam.Hier, 0, 0, 0),
            _ => new(name, Fam.Other, 0, 0, 0)
        };
    }

    private static TypeCompatResult FromInt(N s, N t, ColumnProfile? p) => t.Fam switch
    {
        Fam.Int => t.Rank >= s.Rank || Fits(p, IntMin(t), IntMax(t)) ? WideningResult : Risky($"overflow possible (target {t.Name})"),
        Fam.Dec => t.P - t.S >= s.P || Fits(p, -DecLimit(t), DecLimit(t)) ? WideningResult : Risky($"overflow possible (target {Display(t)})"),
        Fam.Approx => t.P == 24 && s.Rank >= 3 ? Risky("precision loss above 7 significant digits")
            : t.P == 53 && s.Rank == 4 ? Risky("precision loss above 15 significant digits")
            : WideningResult,
        Fam.Bit => Risky("non-zero values become 1"),
        Fam.Str => ToText(t, s.Rank == 1 ? 3 : s.P + 1),
        Fam.Variant => WideningResult,
        Fam.DateTime => NumberToDateTime(s, t),
        Fam.Bin => RawBytes,
        _ => Cannot(s, t)
    };

    private static TypeCompatResult FromDec(N s, N t, ColumnProfile? p)
    {
        var risks = new List<string>();
        switch (t.Fam)
        {
            case Fam.Int:
                if (s.S > 0) risks.Add("fractional part truncated");
                if (s.P - s.S > t.P - 1 && !Fits(p, IntMin(t), IntMax(t))) risks.Add($"overflow possible (target {t.Name})");
                return Combine(risks);
            case Fam.Dec:
                if (t.P - t.S < s.P - s.S && !Fits(p, -DecLimit(t), DecLimit(t))) risks.Add($"overflow possible (target {Display(t)})");
                if (t.S < s.S) risks.Add($"rounded to {t.S} decimal places");
                return Combine(risks);
            case Fam.Approx:
                return s.P <= (t.P == 24 ? 7 : 15) ? WideningResult : Risky("precision loss (approximate type)");
            case Fam.Bit:
                return Risky("non-zero values become 1");
            case Fam.Str:
                return ToText(t, s.P + (s.S > 0 ? 1 : 0) + 1);
            case Fam.Variant:
                return WideningResult;
            case Fam.DateTime:
                return NumberToDateTime(s, t);
            case Fam.Bin:
                return RawBytes;
            default:
                return Cannot(s, t);
        }
    }

    private static TypeCompatResult FromApprox(N s, N t) => t.Fam switch
    {
        Fam.Approx => t.P >= s.P ? WideningResult : Risky("precision loss (float to real)"),
        Fam.Int or Fam.Dec => Risky("rounding or overflow possible"),
        Fam.Bit => Risky("non-zero values become 1"),
        Fam.Str => Risky("string conversion rounds to 6 significant digits unless CONVERT style 3 is used"),
        Fam.Variant => WideningResult,
        Fam.DateTime => NumberToDateTime(s, t),
        Fam.Bin => RawBytes,
        _ => Cannot(s, t)
    };

    private static TypeCompatResult FromBit(N s, N t) => t.Fam switch
    {
        Fam.Int or Fam.Dec or Fam.Approx or Fam.Variant => WideningResult,
        Fam.Str => ToText(t, 1),
        Fam.DateTime => NumberToDateTime(s, t),
        Fam.Bin => RawBytes,
        _ => Cannot(s, t)
    };

    private static TypeCompatResult FromStr(N s, N t, ColumnProfile? p) => t.Fam switch
    {
        Fam.Str => StrToStr(s, t, p),
        Fam.Bit => Risky("needs a CASE transform"),
        Fam.Int or Fam.Dec or Fam.Approx or Fam.Date or Fam.Time or Fam.DateTime or Fam.Guid or Fam.Hier => Risky("conversion may fail"),
        Fam.Xml => Risky("conversion may fail (must be well-formed XML)"),
        Fam.Bin => Risky("converted to raw bytes"),
        Fam.Variant => s.Len == Max ? Incompatible("sql_variant cannot hold (max) or LOB values") : WideningResult,
        Fam.Spatial => Risky("conversion may fail (must be WKT text)"),
        _ => Cannot(s, t)
    };

    private static TypeCompatResult StrToStr(N s, N t, ColumnProfile? p)
    {
        var risks = new List<string>();
        if (s.Unicode && !t.Unicode) risks.Add("non-ASCII characters may be lost");
        if (t.Len < s.Len)
        {
            var observed = p?.MaxLen;
            if (observed is null || observed > t.Len)
                risks.Add(observed is int m ? $"may truncate (source max {m})"
                    : s.Len == Max ? "may truncate (source length unbounded)"
                    : $"may truncate (source max {s.Len})");
        }
        return Combine(risks);
    }

    private static TypeCompatResult FromBin(N s, N t, ColumnProfile? p)
    {
        switch (t.Fam)
        {
            case Fam.Bin:
                if (t.Len >= s.Len || p?.MaxLen is int fits && fits <= t.Len) return WideningResult;
                return Risky(p?.MaxLen is int m ? $"may truncate (source max {m} bytes)"
                    : s.Len == Max ? "may truncate (source length unbounded)"
                    : $"may truncate (source max {s.Len} bytes)");
            case Fam.Str:
                return Risky("bytes reinterpreted as characters");
            case Fam.Guid:
                return Risky("conversion may fail");
            case Fam.Date:
                return Risky("conversion may fail (bytes reinterpreted as a date)");
            case Fam.Variant:
                return s.Len == Max ? Incompatible("sql_variant cannot hold (max) or LOB values") : WideningResult;
            default:
                return Cannot(s, t);
        }
    }

    private static TypeCompatResult FromDate(N s, N t, ColumnProfile? p) => t.Fam switch
    {
        Fam.DateTime => t.Name switch
        {
            "smalldatetime" => DatesWithin(p, 1900, 2079) ? WideningResult : Risky("dates outside 1900-2079 fail"),
            "datetime" => DatesWithin(p, 1753, 9999) ? WideningResult : Risky("dates before 1753 fail"),
            "datetimeoffset" => Risky("time zone offset assumed +00:00"),
            _ => WideningResult
        },
        Fam.Str => ToText(t, 10),
        Fam.Variant => WideningResult,
        Fam.Bin => RawBytes,
        _ => Cannot(s, t)
    };

    private static TypeCompatResult FromTime(N s, N t) => t.Fam switch
    {
        Fam.Time => t.S >= s.S ? WideningResult : Risky($"fractional seconds rounded to {t.S} digits"),
        Fam.DateTime => Risky("date part set to 1900-01-01"),
        Fam.Str => ToText(t, 8 + (s.S > 0 ? s.S + 1 : 0)),
        Fam.Variant => WideningResult,
        _ => Cannot(s, t)
    };

    private static TypeCompatResult FromDateTime(N s, N t, ColumnProfile? p)
    {
        switch (t.Fam)
        {
            case Fam.DateTime:
                var risks = new List<string>();
                if (t.Name == "smalldatetime")
                {
                    if (s.Name != "smalldatetime") risks.Add("seconds dropped");
                    if (!DatesWithin(p, 1900, 2079)) risks.Add("dates outside 1900-2079 fail");
                }
                else if (t.Name == "datetime")
                {
                    if (s.Name is "datetime2" or "datetimeoffset")
                    {
                        if (s.S > 0) risks.Add("fractional seconds rounded to 1/300 s");
                        if (!DatesWithin(p, 1753, 9999)) risks.Add("dates before 1753 fail");
                    }
                }
                else if (t.S < s.S)
                {
                    risks.Add($"fractional seconds rounded to {t.S} digits");
                }
                if (s.Offset && !t.Offset) risks.Add("time zone offset dropped");
                if (!s.Offset && t.Offset) risks.Add("time zone offset assumed +00:00");
                return Combine(risks);
            case Fam.Date:
                return Risky("time part dropped");
            case Fam.Time:
                return Risky("date part dropped");
            case Fam.Int or Fam.Dec or Fam.Approx:
                return s.Name is "datetime" or "smalldatetime" ? Risky("converted to a day number since 1900-01-01") : Cannot(s, t);
            case Fam.Bin:
                return RawBytes;
            case Fam.Str:
                return ToText(t, 19 + (s.S > 0 ? s.S + 1 : 0) + (s.Offset ? 7 : 0));
            case Fam.Variant:
                return WideningResult;
            default:
                return Cannot(s, t);
        }
    }

    private static TypeCompatResult FromGuid(N s, N t) => t.Fam switch
    {
        Fam.Str => ToText(t, 36),
        Fam.Bin => Risky("stored as 16 raw bytes"),
        Fam.Variant => WideningResult,
        _ => Cannot(s, t)
    };

    private static TypeCompatResult NumberToDateTime(N s, N t) =>
        t.Name is "datetime" or "smalldatetime" ? Risky("number interpreted as days since 1900-01-01") : Cannot(s, t);

    private static TypeCompatResult ToText(N t, int needed) =>
        t.Len >= needed ? WideningResult : Risky($"may truncate (needs {needed} characters)");

    private static TypeCompatResult Combine(List<string> risks) =>
        risks.Count == 0 ? WideningResult : Risky(string.Join("; ", risks));

    private static TypeCompatResult Risky(string risk) => new(CompatLevel.Risky, 0.5, risk);
    private static TypeCompatResult Incompatible(string risk) => new(CompatLevel.Incompatible, 0.0, risk);
    private static TypeCompatResult Cannot(N s, N t) => Incompatible($"{s.Name} cannot be converted to {t.Name}");

    private static string Display(N t) => t.Fam == Fam.Dec && t.Name is "decimal" or "numeric" ? $"{t.Name}({t.P},{t.S})" : t.Name;

    private static double IntMin(N t) => t.Name switch { "tinyint" => 0, "smallint" => short.MinValue, "int" => int.MinValue, _ => long.MinValue };
    private static double IntMax(N t) => t.Name switch { "tinyint" => 255, "smallint" => short.MaxValue, "int" => int.MaxValue, _ => long.MaxValue };
    private static double DecLimit(N t) => Math.Pow(10, t.P - t.S) - Math.Pow(10, -t.S);

    private static bool Fits(ColumnProfile? p, double min, double max) =>
        p is not null
        && double.TryParse(p.Min, NumberStyles.Float, CultureInfo.InvariantCulture, out var lo)
        && double.TryParse(p.Max, NumberStyles.Float, CultureInfo.InvariantCulture, out var hi)
        && lo >= min && hi <= max;

    private static bool DatesWithin(ColumnProfile? p, int fromYear, int toYear) =>
        p is not null
        && DateTime.TryParse(p.Min, CultureInfo.InvariantCulture, DateTimeStyles.None, out var lo)
        && DateTime.TryParse(p.Max, CultureInfo.InvariantCulture, DateTimeStyles.None, out var hi)
        && lo.Year >= fromYear && hi.Year <= toYear;
}
